info:
  component: Config Server
spring:
  application:
    name: configserver
  jmx:
    default_domain: cloud.config.server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/jaredhu/config-repo
          repos:
            - patterns: multi-repo-demo-*
              uri: https://github.com/jaredhu/config-repo
server:
  port: 8888
management:
  context_path: /admin
endpoints:
  restart:
    enabled: true
logging:
  levels:
    org.springframework.boot.env.PropertySourcesLoader: TRACE
    org.springframework.web: DEBUG



