info:
  component: Config Samples Test 2
endpoints:
  restart:
    enabled: true
logging:
  levels:
    org.springframework.boot.env.PropertySourcesLoader: TRACE
    org.springframework.web: DEBUG
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/jaredhu/config-repo
